### ISSUE TITLE
Work life balance?

### ISSUE THREAD

**Issue by anshumanv** [evenstensberg/ama#1]
How do you balance all this while working and maintaining open source?

How do you handle burnout?

**Comment by evenstensberg** [comment]
I got different methods to do it. I've got work, university assignments, Open source and some hobbies that I try to maintain. A trick I've learned is to multitask for the things I can multitask, but focus on one thing. For instance, I go to university to work. After I'm done at work, I usually lift weights to get my mind of programming and then I resume my assignments. I occasionally play soccer between the different things, and it's fun! 

This means that I've reduced the risk of burning out while being effective. University and job comes first and then it's just a matter of prioritizing what you want to do. 

When I feel I'm burning out I usually relax for a while, watching a movie or exercise.
